name = "Imbigo Theme"
license = "GPL-3.0"
licenselink = "https://github.com/matheus/imbigo/blob/main/LICENSE"
description = "A modern, lightweight personal website theme"
homepage = "https://imbigo.net"
tags = ["blog", "personal", "minimal", "responsive"]
features = ["responsive", "blog", "portfolio"]
min_version = "0.140.0"

[author]
  name = "Matheus Mendes"
  homepage = "https://imbigo.net"
