baseURL = 'https://imbigo.net/'
languageCode = 'en-us'
title = ''
theme = 'imbigo-theme'

[params]
  author = 'Matheus Mendes'
  description = 'tech, startups and bad advice from 20 years of coding'
  
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Code"
    url = "/code/"
    weight = 3
[caches]
  [caches.images]
    dir = ':cacheDir/images'
