baseURL = 'https://imbigo.net/'
languageCode = 'en-us'
title = 'Matheus Mendes'
theme = 'imbigo-theme'

[params]
  author = 'Matheus Mendes'
  description = 'Personal website and blog'
  
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Code"
    url = "/code/"
    weight = 3
